### ISSUE TITLE
Inter-f1和Intra-f1

### ISSUE THREAD

**Issue by xbcml** [BurgerBurgerBurger/AA#1]
您好，能介绍一下您们是怎么计算Inter-f1和Intra-f1这两个指标的吗

**Comment by wucui5** [comment]
> 您好，能介绍一下您们是怎么计算Inter-f1和Intra-f1这两个指标的吗

你好，请问一下你有复现成功这个代码吗

**Comment by xbcml** [comment]
> > 您好，能介绍一下您们是怎么计算Inter-f1和Intra-f1这两个指标的吗
> 
> 你好，请问一下你有复现成功这个代码吗
我参考了这个里面的代码，复现成功了
https://github.com/AndrewZhe/Three-Sentences-Are-All-You-Need/blob/533189ccee363731215110ff323c648fbf86585a/src/eval_submmit.py#L43

**Comment by wucui5** [comment]
> > > 您好，能介绍一下您们是怎么计算Inter-f1和Intra-f1这两个指标的吗
> > 
> > 
> > 你好，请问一下你有复现成功这个代码吗
> > 我参考了这个里面的代码，复现成功了
> > https://github.com/AndrewZhe/Three-Sentences-Are-All-You-Need/blob/533189ccee363731215110ff323c648fbf86585a/src/eval_submmit.py#L43

你好，你这个复现结果怎么样，我复现出来和论文中有一定差距，大概是0.6-1分的差距

**Comment by xbcml** [comment]
> > > > 您好，能介绍一下您们是怎么计算Inter-f1和Intra-f1这两个指标的吗
> > > 
> > > 
> > > 你好，请问一下你有复现成功这个代码吗
> > > 我参考了这个里面的代码，复现成功了
> > > https://github.com/AndrewZhe/Three-Sentences-Are-All-You-Need/blob/533189ccee363731215110ff323c648fbf86585a/src/eval_submmit.py#L43
> 
> 你好，你这个复现结果怎么样，我复现出来和论文中有一定差距，大概是0.6-1分的差距

我还没复现这篇论文的结果，近期准备复现，我结果出来后看一下

**Comment by wucui5** [comment]
> > > > > 您好，能介绍一下您们是怎么计算Inter-f1和Intra-f1这两个指标的吗
> > > > 
> > > > 
> > > > 你好，请问一下你有复现成功这个代码吗
> > > > 我参考了这个里面的代码，复现成功了
> > > > https://github.com/AndrewZhe/Three-Sentences-Are-All-You-Need/blob/533189ccee363731215110ff323c648fbf86585a/src/eval_submmit.py#L43
> > 
> > 
> > 你好，你这个复现结果怎么样，我复现出来和论文中有一定差距，大概是0.6-1分的差距
> 
> 我还没复现这篇论文的结果，近期准备复现，我结果出来后看一下

好的，非常感谢，复现有什么问题可以问我，然后结果出来了咱们对比一下

**Comment by xbcml** [comment]
> > > > > > 您好，能介绍一下您们是怎么计算Inter-f1和Intra-f1这两个指标的吗
> > > > > 
> > > > > 
> > > > > 你好，请问一下你有复现成功这个代码吗
> > > > > 我参考了这个里面的代码，复现成功了
> > > > > https://github.com/AndrewZhe/Three-Sentences-Are-All-You-Need/blob/533189ccee363731215110ff323c648fbf86585a/src/eval_submmit.py#L43
> > > 
> > > 
> > > 你好，你这个复现结果怎么样，我复现出来和论文中有一定差距，大概是0.6-1分的差距
> > 
> > 
> > 我还没复现这篇论文的结果，近期准备复现，我结果出来后看一下
> 
> 好的，非常感谢，复现有什么问题可以问我，然后结果出来了咱们对比一下

Traceback (most recent call last):
  File "/home/user/lyx/Programs/AA-main/run.py", line 356, in <module>
    main()
  File "/home/user/lyx/Programs/AA-main/run.py", line 301, in main
    train(args, model, train_features, dev_features)
  File "/home/user/lyx/Programs/AA-main/run.py", line 123, in train
    finetune(train_features, optimizer, args.num_train_epochs, num_steps)
  File "/home/user/lyx/Programs/AA-main/run.py", line 86, in finetune
    dev_scores, dev_output, official_results, results = evaluate(args, model, dev_features, tag="dev")
  File "/home/user/lyx/Programs/AA-main/run.py", line 170, in evaluate
    official_results, results = to_official(preds, features, evi_preds=evi_preds, scores=scores, topks=topks)
  File "/home/user/lyx/Programs/AA-main/evaluation.py", line 198, in to_official
    if scores != []:
ValueError: operands could not be broadcast together with shapes (395572,4) (0,) 
在训练过程中你有遇到这个问题吗

**Comment by wucui5** [comment]
> > > > > > > 您好，能介绍一下您们是怎么计算Inter-f1和Intra-f1这两个指标的吗
> > > > > > 
> > > > > > 
> > > > > > 你好，请问一下你有复现成功这个代码吗
> > > > > > 我参考了这个里面的代码，复现成功了
> > > > > > https://github.com/AndrewZhe/Three-Sentences-Are-All-You-Need/blob/533189ccee363731215110ff323c648fbf86585a/src/eval_submmit.py#L43
> > > > 
> > > > 
> > > > 你好，你这个复现结果怎么样，我复现出来和论文中有一定差距，大概是0.6-1分的差距
> > > 
> > > 
> > > 我还没复现这篇论文的结果，近期准备复现，我结果出来后看一下
> > 
> > 
> > 好的，非常感谢，复现有什么问题可以问我，然后结果出来了咱们对比一下
> 
> Traceback (most recent call last): File "/home/user/lyx/Programs/AA-main/run.py", line 356, in main() File "/home/user/lyx/Programs/AA-main/run.py", line 301, in main train(args, model, train_features, dev_features) File "/home/user/lyx/Programs/AA-main/run.py", line 123, in train finetune(train_features, optimizer, args.num_train_epochs, num_steps) File "/home/user/lyx/Programs/AA-main/run.py", line 86, in finetune dev_scores, dev_output, official_results, results = evaluate(args, model, dev_features, tag="dev") File "/home/user/lyx/Programs/AA-main/run.py", line 170, in evaluate official_results, results = to_official(preds, features, evi_preds=evi_preds, scores=scores, topks=topks) File "/home/user/lyx/Programs/AA-main/evaluation.py", line 198, in to_official if scores != []: ValueError: operands could not be broadcast together with shapes (395572,4) (0,) 在训练过程中你有遇到这个问题吗
我没有遇到过这个问题欸，你可以再检查一下代码

**Comment by wucui5** [comment]
> > > > > > > 您好，能介绍一下您们是怎么计算Inter-f1和Intra-f1这两个指标的吗
> > > > > > 
> > > > > > 
> > > > > > 你好，请问一下你有复现成功这个代码吗
> > > > > > 我参考了这个里面的代码，复现成功了
> > > > > > https://github.com/AndrewZhe/Three-Sentences-Are-All-You-Need/blob/533189ccee363731215110ff323c648fbf86585a/src/eval_submmit.py#L43
> > > > 
> > > > 
> > > > 你好，你这个复现结果怎么样，我复现出来和论文中有一定差距，大概是0.6-1分的差距
> > > 
> > > 
> > > 我还没复现这篇论文的结果，近期准备复现，我结果出来后看一下
> > 
> > 
> > 好的，非常感谢，复现有什么问题可以问我，然后结果出来了咱们对比一下
> 
> Traceback (most recent call last): File "/home/user/lyx/Programs/AA-main/run.py", line 356, in main() File "/home/user/lyx/Programs/AA-main/run.py", line 301, in main train(args, model, train_features, dev_features) File "/home/user/lyx/Programs/AA-main/run.py", line 123, in train finetune(train_features, optimizer, args.num_train_epochs, num_steps) File "/home/user/lyx/Programs/AA-main/run.py", line 86, in finetune dev_scores, dev_output, official_results, results = evaluate(args, model, dev_features, tag="dev") File "/home/user/lyx/Programs/AA-main/run.py", line 170, in evaluate official_results, results = to_official(preds, features, evi_preds=evi_preds, scores=scores, topks=topks) File "/home/user/lyx/Programs/AA-main/evaluation.py", line 198, in to_official if scores != []: ValueError: operands could not be broadcast together with shapes (395572,4) (0,) 在训练过程中你有遇到这个问题吗

你现在有复现出来吗

**Comment by xbcml** [comment]
> > > > > > > > 您好，能介绍一下您们是怎么计算Inter-f1和Intra-f1这两个指标的吗
> > > > > > > 
> > > > > > > 
> > > > > > > 你好，请问一下你有复现成功这个代码吗
> > > > > > > 我参考了这个里面的代码，复现成功了
> > > > > > > https://github.com/AndrewZhe/Three-Sentences-Are-All-You-Need/blob/533189ccee363731215110ff323c648fbf86585a/src/eval_submmit.py#L43
> > > > > 
> > > > > 
> > > > > 你好，你这个复现结果怎么样，我复现出来和论文中有一定差距，大概是0.6-1分的差距
> > > > 
> > > > 
> > > > 我还没复现这篇论文的结果，近期准备复现，我结果出来后看一下
> > > 
> > > 
> > > 好的，非常感谢，复现有什么问题可以问我，然后结果出来了咱们对比一下
> > 
> > 
> > Traceback (most recent call last): File "/home/user/lyx/Programs/AA-main/run.py", line 356, in main() File "/home/user/lyx/Programs/AA-main/run.py", line 301, in main train(args, model, train_features, dev_features) File "/home/user/lyx/Programs/AA-main/run.py", line 123, in train finetune(train_features, optimizer, args.num_train_epochs, num_steps) File "/home/user/lyx/Programs/AA-main/run.py", line 86, in finetune dev_scores, dev_output, official_results, results = evaluate(args, model, dev_features, tag="dev") File "/home/user/lyx/Programs/AA-main/run.py", line 170, in evaluate official_results, results = to_official(preds, features, evi_preds=evi_preds, scores=scores, topks=topks) File "/home/user/lyx/Programs/AA-main/evaluation.py", line 198, in to_official if scores != []: ValueError: operands could not be broadcast together with shapes (395572,4) (0,) 在训练过程中你有遇到这个问题吗
> 
> 你现在有复现出来吗

我使用bert模型进行实验，在DOCRED上的结果F1为62.54

**Comment by wucui5** [comment]
> > > > > > > > > 您好，能介绍一下您们是怎么计算Inter-f1和Intra-f1这两个指标的吗
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 你好，请问一下你有复现成功这个代码吗
> > > > > > > > 我参考了这个里面的代码，复现成功了
> > > > > > > > https://github.com/AndrewZhe/Three-Sentences-Are-All-You-Need/blob/533189ccee363731215110ff323c648fbf86585a/src/eval_submmit.py#L43
> > > > > > 
> > > > > > 
> > > > > > 你好，你这个复现结果怎么样，我复现出来和论文中有一定差距，大概是0.6-1分的差距
> > > > > 
> > > > > 
> > > > > 我还没复现这篇论文的结果，近期准备复现，我结果出来后看一下
> > > > 
> > > > 
> > > > 好的，非常感谢，复现有什么问题可以问我，然后结果出来了咱们对比一下
> > > 
> > > 
> > > Traceback (most recent call last): File "/home/user/lyx/Programs/AA-main/run.py", line 356, in main() File "/home/user/lyx/Programs/AA-main/run.py", line 301, in main train(args, model, train_features, dev_features) File "/home/user/lyx/Programs/AA-main/run.py", line 123, in train finetune(train_features, optimizer, args.num_train_epochs, num_steps) File "/home/user/lyx/Programs/AA-main/run.py", line 86, in finetune dev_scores, dev_output, official_results, results = evaluate(args, model, dev_features, tag="dev") File "/home/user/lyx/Programs/AA-main/run.py", line 170, in evaluate official_results, results = to_official(preds, features, evi_preds=evi_preds, scores=scores, topks=topks) File "/home/user/lyx/Programs/AA-main/evaluation.py", line 198, in to_official if scores != []: ValueError: operands could not be broadcast together with shapes (395572,4) (0,) 在训练过程中你有遇到这个问题吗
> > 
> > 
> > 你现在有复现出来吗
> 
> 我使用bert模型进行实验，在DOCRED上的结果F1为62.54

我也是差不多这个分数

**Comment by BurgerBurgerBurger** [comment]
> 您好，能介绍一下您们是怎么计算Inter-f1和Intra-f1这两个指标的吗

您好，关于Inter-f1和Intra-f1可以参照这个实现 
https://github.com/tonytan48/Re-DocRED/blob/ccfb54f5ddf5836027c87badda10f6dfc56efaac/evaluation.py
